import { ArrowRight, Check, ClipboardCheck, GitMerge, ShieldCheck, Sparkles } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { ReviewPanel } from "../components/review/ReviewPanel";
import { useBlocks } from "../hooks/useBlocks";
import { Alert, AlertDescription, AlertTitle } from "../components/ui/alert";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card, CardContent } from "../components/ui/card";
import { EmptyState } from "../components/ui/EmptyState";
import { LoadingSpinner } from "../components/ui/LoadingSpinner";
import { demoDashboard, demoDepartments } from "../data/demo";

function DemoRecommendation() {
  const recommendation = demoDashboard.blockRecommendations[0];
  return <Card className="border-accent/25 bg-surface/80"><CardContent className="p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-center gap-2"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-accent/10 text-accent"><GitMerge className="h-4 w-4" /></div><div><div className="font-mono text-[10px] uppercase tracking-[0.16em] text-accent">Example recommendation</div><div className="mt-1 text-sm font-medium text-text-primary">{recommendation.section} <span className="font-mono text-xs font-normal text-text-muted">KM {recommendation.km}</span></div></div></div><Badge variant="warning">Preview</Badge></div><div className="mt-6 grid gap-5 lg:grid-cols-[1fr_0.75fr]"><div><div className="flex flex-wrap gap-2">{recommendation.departments.map((department) => { const item = demoDepartments.find((candidate) => candidate.code === department); return <span key={department} className="rounded-md border border-border bg-surface2 px-2.5 py-1.5 font-mono text-[9px] uppercase tracking-[0.12em] text-text-secondary">{item?.label || department}</span>; })}</div><p className="mt-5 text-sm leading-6 text-text-secondary">{recommendation.reason} The proposal is ready for an officer to compare timing, access, and compatibility before approval.</p></div><div className="rounded-lg border border-border bg-surface2/50 p-4"><div className="data-label">Why it appears</div><div className="mt-3 space-y-2 text-xs text-text-secondary"><div className="flex items-center gap-2"><Check className="h-3.5 w-3.5 text-status-safe" /> Same section</div><div className="flex items-center gap-2"><Check className="h-3.5 w-3.5 text-status-safe" /> Overlapping work window</div><div className="flex items-center gap-2"><Check className="h-3.5 w-3.5 text-status-safe" /> Compatible work</div></div><div className="mt-4 flex items-center gap-2 border-t border-border pt-3 text-[10px] text-text-muted"><Sparkles className="h-3.5 w-3.5 text-accent" /> AI recommends; officers decide.</div></div></div><div className="mt-5 flex items-center gap-2 border-t border-border pt-4 text-xs text-text-muted"><ClipboardCheck className="h-3.5 w-3.5" /> This example is demo data. Submit compatible requests to create a live proposal.</div></CardContent></Card>;
}

export function ReviewPage() {
  const { blocks, loading, error, reviewBlock } = useBlocks();
  const navigate = useNavigate();
  if (loading && blocks.length === 0) return <LoadingSpinner />;
  const proposedBlocks = blocks.filter((block) => block.status.toUpperCase() === "PROPOSED");
  const pastBlocks = blocks.filter((block) => block.status.toUpperCase() !== "PROPOSED");

  return <div className="mx-auto max-w-6xl space-y-5 pb-10 animate-fade-up"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-xs text-text-muted"><Link to="/operations" className="hover:text-text-primary">Overview</Link><span className="text-border-strong">/</span><span>Review</span></div><div className="mt-3 flex flex-wrap items-center gap-3"><h1 className="text-2xl font-semibold tracking-[-0.035em] text-text-primary sm:text-3xl">Officer review queue</h1><Badge variant={proposedBlocks.length ? "warning" : "success"}>{proposedBlocks.length} pending</Badge></div><p className="mt-2 text-sm text-text-secondary">Recommendations become decisions only after an operations officer reviews them.</p></div><Button asChild variant="outline" size="sm"><Link to="/blocks">View all blocks <ArrowRight className="h-3.5 w-3.5" /></Link></Button></div>{error && <div className="rounded-lg border border-status-emergency/30 bg-status-emergency/10 p-3 text-sm text-status-emergency">{error}</div>}<Alert className="border-status-warning/25 bg-status-warning/[0.06]"><ShieldCheck className="h-4 w-4 text-status-warning" /><AlertTitle className="text-status-warning">Human approval is required</AlertTitle><AlertDescription>Approving a block updates its linked requests. Samanvay never auto-approves work.</AlertDescription></Alert><div className="space-y-4"><div className="flex items-center gap-2"><ClipboardCheck className="h-4 w-4 text-accent" /><h2 className="text-sm font-medium text-text-primary">Pending proposals</h2><span className="font-mono text-[10px] text-text-muted">({proposedBlocks.length})</span></div>{proposedBlocks.length === 0 ? <><EmptyState title="No pending proposals" message="Your corridor is clear for now. When compatible requests are submitted, a live recommendation will appear here." actionLabel="Create a request" onAction={() => navigate("/new-request")} /><DemoRecommendation /></> : proposedBlocks.map((block) => <ReviewPanel key={block.block_id} block={block} onReview={reviewBlock} />)}</div>{pastBlocks.length > 0 && <div className="space-y-4 border-t border-border pt-6"><div className="flex items-center gap-2"><ClipboardCheck className="h-4 w-4 text-text-muted" /><h2 className="text-sm font-medium text-text-primary">Recent reviews</h2><span className="font-mono text-[10px] text-text-muted">({pastBlocks.length})</span></div>{pastBlocks.map((block) => <ReviewPanel key={block.block_id} block={block} onReview={reviewBlock} />)}</div>}<Card className="bg-surface/50"><CardContent className="flex flex-col gap-2 p-4 text-xs text-text-muted sm:flex-row sm:items-center sm:justify-between"><span>Review actions are recorded in the audit history.</span><Link to="/audit" className="inline-flex items-center gap-1 text-accent hover:underline">Open audit log <ArrowRight className="h-3 w-3" /></Link></CardContent></Card></div>;
}
